In [1]:
import pandas as pd
import numpy as np
from scipy.signal import argrelextrema
from scipy.signal import find_peaks
from itertools import product
from tqdm import tqdm
import time
import numba as nb
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import talib as ta
from tqdm import tqdm

In [2]:
df=pd.read_csv('../EUR_USD_2020_M5.csv')

In [3]:
df.set_index('time',inplace=True)

In [4]:
class RSI_divergence():

    def __init__(self,data):

        self.data=data

        self.params_range={'window':[10,14,20,30],
                          'up_level':[60,70,80],
                          'down_level':[20,30,40]}

    def create_params_combs(self):

        return list(product(*self.params_range.values()))

In [5]:
rsid=RSI_divergence(df)

In [6]:
len(rsid.create_params_combs())

36

In [7]:
df['RSI']=ta.RSI(df['c'],14)

In [8]:
df.iloc[50:100]

,o,h,l,c,volume,complete,RSI
time,,,,,,,
2020-01-02 02:25:00+00:00,1.12204,1.12216,1.12202,1.12216,14,True,57.081534
2020-01-02 02:30:00+00:00,1.12214,1.12222,1.12214,1.12222,8,True,59.182797
2020-01-02 02:35:00+00:00,1.12224,1.12234,1.12224,1.12231,6,True,62.174362
2020-01-02 02:40:00+00:00,1.12233,1.12239,1.12231,1.12239,9,True,64.654210
2020-01-02 02:45:00+00:00,1.12242,1.12244,1.12242,1.12244,2,True,66.147995
2020-01-02 02:50:00+00:00,1.12247,1.12247,1.12244,1.12244,4,True,66.147995
2020-01-02 02:55:00+00:00,1.12242,1.12242,1.12220,1.12224,14,True,55.305110
2020-01-02 03:00:00+00:00,1.12222,1.12227,1.12219,1.12227,11,True,56.458063
2020-01-02 03:05:00+00:00,1.12229,1.12232,1.12229,1.12230,7,True,57.634981
2020-01-02 03:10:00+00:00,1.12227,1.12227,1.12217,1.12217,5,True,51.179335
2020-01-02 03:15:00+00:00,1.12215,1.12216,1.12193,1.12193,16,True,41.857885
2020-01-02 03:20:00+00:00,1.12196,1.12198,1.12188,1.12196,11,True,43.249294
2020-01-02 03:25:00+00:00,1.12198,1.12199,1.12182,1.12182,18,True,38.606152
2020-01-02 03:30:00+00:00,1.12180,1.12180,1.12159,1.12164,23,True,33.610051
2020-01-02 03:35:00+00:00,1.12162,1.12169,1.12160,1.12160,17,True,32.600403
2020-01-02 03:40:00+00:00,1.12162,1.12162,1.12133,1.12138,26,True,27.676022
2020-01-02 03:45:00+00:00,1.12136,1.12143,1.12133,1.12136,22,True,27.272702
2020-01-02 03:50:00+00:00,1.12132,1.12133,1.12124,1.12132,11,True,26.442725
2020-01-02 03:55:00+00:00,1.12135,1.12138,1.12130,1.12132,8,True,26.442725
2020-01-02 04:00:00+00:00,1.12135,1.12135,1.12130,1.12133,6,True,27.086091
2020-01-02 04:05:00+00:00,1.12130,1.12134,1.12126,1.12134,13,True,27.766477
2020-01-02 04:10:00+00:00,1.12137,1.12142,1.12134,1.12142,9,True,33.141456
2020-01-02 04:15:00+00:00,1.12140,1.12142,1.12140,1.12142,4,True,33.141456
2020-01-02 04:20:00+00:00,1.12140,1.12140,1.12126,1.12128,10,True,28.793024
2020-01-02 04:25:00+00:00,1.12126,1.12128,1.12120,1.12122,6,True,27.148948
2020-01-02 04:30:00+00:00,1.12120,1.12121,1.12110,1.12119,21,True,26.339124
2020-01-02 04:35:00+00:00,1.12116,1.12116,1.12108,1.12108,14,True,23.563654
2020-01-02 04:40:00+00:00,1.12105,1.12107,1.12091,1.12098,16,True,21.360069
2020-01-02 04:45:00+00:00,1.12100,1.12100,1.12076,1.12076,19,True,17.485871
2020-01-02 04:50:00+00:00,1.12074,1.12074,1.12043,1.12048,30,True,14.004394
2020-01-02 04:55:00+00:00,1.12046,1.12046,1.12010,1.12012,47,True,10.977983
2020-01-02 05:00:00+00:00,1.12014,1.12020,1.12012,1.12014,21,True,12.114286
2020-01-02 05:05:00+00:00,1.12016,1.12029,1.12014,1.12029,16,True,20.328150
2020-01-02 05:10:00+00:00,1.12032,1.12034,1.12014,1.12014,16,True,18.469222
2020-01-02 05:15:00+00:00,1.12016,1.12030,1.12011,1.12026,26,True,24.423462
2020-01-02 05:20:00+00:00,1.12029,1.12034,1.12028,1.12028,19,True,25.401305
2020-01-02 05:25:00+00:00,1.12026,1.12029,1.12014,1.12018,22,True,23.746893
2020-01-02 05:30:00+00:00,1.12021,1.12028,1.12014,1.12025,17,True,27.315606
2020-01-02 05:35:00+00:00,1.12023,1.12028,1.12023,1.12026,6,True,27.835203
2020-01-02 05:40:00+00:00,1.12028,1.12033,1.12028,1.12030,14,True,29.991076
2020-01-02 05:45:00+00:00,1.12028,1.12028,1.12018,1.12024,18,True,28.610382
2020-01-02 05:50:00+00:00,1.12026,1.12036,1.12026,1.12036,5,True,35.050526
2020-01-02 05:55:00+00:00,1.12039,1.12044,1.12030,1.12044,13,True,39.001235
2020-01-02 06:00:00+00:00,1.12044,1.12066,1.12044,1.12066,29,True,48.312384
2020-01-02 06:05:00+00:00,1.12064,1.12072,1.12064,1.12064,15,True,47.601022
2020-01-02 06:10:00+00:00,1.12066,1.12071,1.12064,1.12068,30,True,49.211706
2020-01-02 06:15:00+00:00,1.12066,1.12069,1.12054,1.12058,22,True,45.450310
2020-01-02 06:20:00+00:00,1.12061,1.12063,1.12056,1.12062,16,True,47.189107
2020-01-02 06:25:00+00:00,1.12060,1.12064,1.12044,1.12054,31,True,44.157482
2020-01-02 06:30:00+00:00,1.12056,1.12056,1.12039,1.12046,23,True,41.300092

In [9]:
def calc_div(window, low, rsi):

    min_close=close.iloc[0]
    max_close=close.iloc[0]

    min_rsi=rsi.iloc[0]
    max_rsi=rsi.iloc[0]

    for i in range(len(close)):

        if close.iloc[i]>=max_close:
            max_close=close[i]

        if close.iloc[i]<=min_close:
            min_close=close.iloc[i]

        
    return max_close, min_close

In [10]:
vals=df['c'].iloc[20:30]

In [11]:
vals

time
2020-01-01 23:55:00+00:00    1.12189
2020-01-02 00:00:00+00:00    1.12192
2020-01-02 00:05:00+00:00    1.12184
2020-01-02 00:10:00+00:00    1.12162
2020-01-02 00:15:00+00:00    1.12164
2020-01-02 00:20:00+00:00    1.12162
2020-01-02 00:25:00+00:00    1.12162
2020-01-02 00:30:00+00:00    1.12166
2020-01-02 00:35:00+00:00    1.12159
2020-01-02 00:40:00+00:00    1.12175
Name: c, dtype: float64

In [12]:
slopes_vals=np.gradient(vals)

In [13]:
slopes_vals

array([ 3.0e-05, -2.5e-05, -1.5e-04, -1.0e-04,  0.0e+00, -1.0e-05,
        2.0e-05, -1.5e-05,  4.5e-05,  1.6e-04])

In [14]:
np.sum(slopes_vals)

np.float64(-4.500000000007276e-05)

In [15]:
rsi=df['RSI'].iloc[20:30]

In [16]:
slopes_rsi=np.gradient(rsi)

In [17]:
np.sum(slopes_rsi)

np.float64(-4.44937258022426)

In [18]:
rsi

time
2020-01-01 23:55:00+00:00    64.674280
2020-01-02 00:00:00+00:00    65.673589
2020-01-02 00:05:00+00:00    60.739225
2020-01-02 00:10:00+00:00    49.683860
2020-01-02 00:15:00+00:00    50.564772
2020-01-02 00:20:00+00:00    49.629052
2020-01-02 00:25:00+00:00    49.629052
2020-01-02 00:30:00+00:00    51.702173
2020-01-02 00:35:00+00:00    47.980549
2020-01-02 00:40:00+00:00    55.810352
Name: RSI, dtype: float64

In [19]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn import set_config
set_config(transform_output = "pandas")

In [20]:
rsi_vals=df.loc[:,['c','RSI']].iloc[30:80]

In [21]:
scaler_st=StandardScaler()

In [22]:
rsi_vals

                                 c        RSI
time
2020-01-02 00:45:00+00:00  1.12184  59.502823
2020-01-02 00:50:00+00:00  1.12184  59.502823
2020-01-02 00:55:00+00:00  1.12184  59.502823
2020-01-02 01:00:00+00:00  1.12218  70.954438
2020-01-02 01:05:00+00:00  1.12208  65.121687
2020-01-02 01:10:00+00:00  1.12227  70.143604
2020-01-02 01:15:00+00:00  1.12240  73.007347
2020-01-02 01:20:00+00:00  1.12238  71.865292
2020-01-02 01:25:00+00:00  1.12238  71.865292
2020-01-02 01:30:00+00:00  1.12233  68.747227
2020-01-02 01:35:00+00:00  1.12234  69.036581
2020-01-02 01:40:00+00:00  1.12212  56.617275
2020-01-02 01:45:00+00:00  1.12203  52.459626
2020-01-02 01:50:00+00:00  1.12190  47.081460
2020-01-02 01:55:00+00:00  1.12209  54.434109
2020-01-02 02:00:00+00:00  1.12202  51.590097
2020-01-02 02:05:00+00:00  1.12193  48.109749
2020-01-02 02:10:00+00:00  1.12190  46.972225
2020-01-02 02:15:00+00:00  1.12204  52.604180
2020-01-02 02:20:00+00:00  1.12206  53.366160
2020-01-02 02:25:00+00:00  1.12216  57.081534
2020-01-02 02:30:00+00:00  1.12222  59.182797
2020-01-02 02:35:00+00:00  1.12231  62.174362
2020-01-02 02:40:00+00:00  1.12239  64.654210
2020-01-02 02:45:00+00:00  1.12244  66.147995
2020-01-02 02:50:00+00:00  1.12244  66.147995
2020-01-02 02:55:00+00:00  1.12224  55.305110
2020-01-02 03:00:00+00:00  1.12227  56.458063
2020-01-02 03:05:00+00:00  1.12230  57.634981
2020-01-02 03:10:00+00:00  1.12217  51.179335
2020-01-02 03:15:00+00:00  1.12193  41.857885
2020-01-02 03:20:00+00:00  1.12196  43.249294
2020-01-02 03:25:00+00:00  1.12182  38.606152
2020-01-02 03:30:00+00:00  1.12164  33.610051
2020-01-02 03:35:00+00:00  1.12160  32.600403
2020-01-02 03:40:00+00:00  1.12138  27.676022
2020-01-02 03:45:00+00:00  1.12136  27.272702
2020-01-02 03:50:00+00:00  1.12132  26.442725
2020-01-02 03:55:00+00:00  1.12132  26.442725
2020-01-02 04:00:00+00:00  1.12133  27.086091
2020-01-02 04:05:00+00:00  1.12134  27.766477
2020-01-02 04:10:00+00:00  1.12142  33.141456
2020-01-02 04:15:00+00:00  1.12142  33.141456
2020-01-02 04:20:00+00:00  1.12128  28.793024
2020-01-02 04:25:00+00:00  1.12122  27.148948
2020-01-02 04:30:00+00:00  1.12119  26.339124
2020-01-02 04:35:00+00:00  1.12108  23.563654
2020-01-02 04:40:00+00:00  1.12098  21.360069
2020-01-02 04:45:00+00:00  1.12076  17.485871
2020-01-02 04:50:00+00:00  1.12048  14.004394

In [23]:
st_df=scaler_st.fit_transform(rsi_vals)

In [24]:
scaler_mm=MinMaxScaler()

In [25]:
mm_df=scaler_mm.fit_transform(rsi_vals)

In [26]:
np.sum(np.gradient(rsi_vals['c'].iloc[:10]))

np.float64(0.00046500000000015973)

In [27]:
np.sum(np.gradient(rsi_vals['RSI'].iloc[:10]))

np.float64(7.6853712109998895)

In [28]:
np.sum(np.gradient(st_df['c'].iloc[:10]))

np.float64(0.9640645835711783)

In [29]:
np.sum(np.gradient(st_df['RSI'].iloc[:10]))

np.float64(0.45246094218974797)

In [30]:
np.sum(np.gradient(mm_df['c'].iloc[:10]))

np.float64(0.23724489795932868)

In [31]:
np.sum(np.gradient(mm_df['RSI'].iloc[:10]))

np.float64(0.13025401041729145)

In [32]:
from sklearn.metrics.pairwise import cosine_similarity

In [33]:
cosine_similarity([rsi_vals['c'].iloc[:10]],[rsi_vals['RSI'].iloc[:10]])

array([[0.99686742]])

In [34]:
cosine_similarity([st_df['c'].iloc[:10]],[st_df['RSI'].iloc[:10]])

array([[0.93517362]])

In [35]:
cosine_similarity([mm_df['c'].iloc[:10]],[mm_df['RSI'].iloc[:10]])

array([[0.99901505]])

In [36]:
ar1=[6,2,3,4,3,4,5,2,1,3,5,6,7,8,9,10]
ar2=[6,2,1,3,4,5,6,4,3,2,1,4,5,4,3,2]

In [37]:
ar2=[val/10 for val in ar2]

In [38]:
ar2

[0.6,
 0.2,
 0.1,
 0.3,
 0.4,
 0.5,
 0.6,
 0.4,
 0.3,
 0.2,
 0.1,
 0.4,
 0.5,
 0.4,
 0.3,
 0.2]

In [39]:
cosine_similarity([ar1],[ar2])

array([[0.83568799]])

In [40]:
np.sum(np.gradient(ar1))

np.float64(2.5)

In [41]:
np.sum(np.gradient(ar2))

np.float64(-0.6499999999999999)

In [ ]:
df_cos=df.iloc[1000:2000]

In [ ]:
cossim=[]
for i in range(len(df_cos)):

    if i>=10:

        rsi_vals=df_cos.loc[:,['c','RSI']].iloc[i-10:i]
        cossimval=cosine_similarity([rsi_vals['c']],[rsi_vals['RSI']])
        cossim.append(cossimval[0][0])

    else:

        cossim.append(np.nan)

In [ ]:
len(cossim)

In [ ]:
df_cos['cossim']=cossim

In [ ]:
#res = (a - a.min()) / (a.max() - a.min())
df_cos['cossim_norm']=(df_cos['cossim'] - df_cos['cossim'].min()) / (df_cos['cossim'].max() - df_cos['cossim'].min())

In [ ]:
import plotly.graph_objects as go
from plotly.subplots import make_subplots

In [ ]:
df_cos

In [ ]:
figure = make_subplots(rows=3, cols=1, row_heights=[0.5,0.25,0.25], shared_xaxes=True,vertical_spacing=0.01)
figure.update_layout(height=800, width=1200, title_text='pos_ch_retr_0.382_per_20')


figure.add_trace(go.Candlestick(x=df_cos.index,
                                open=df_cos['o'],
                                high=df_cos['h'],
                                low=df_cos['l'],
                                close=df_cos['c'],
                                name='price'), row=1, col=1)
figure.add_trace(go.Scatter(x=df_cos.index,y=df_cos['RSI'],mode='lines',line_color='blue',name='cossim'),col=1,row=2 )
figure.add_trace(go.Scatter(x=df_cos.index,y=df_cos['cossim_norm'],mode='lines',line_color='yellow',name='cossim'),col=1,row=3 )
figure.add_hline(y=0.7, col=1,row=3)

figure.update_layout(xaxis_rangeslider_visible=False)
figure.update_xaxes(
        rangebreaks=[
            dict(bounds=["sat", "mon"])]
    )
figure.show()